_target_: vc_models.models.load_model
model:
  _target_: vc_models.models.vit.vit.load_spa_encoder
  model:
    _target_: spa.models.spa_vit_large_patch16
    pretrained: true
transform:
  _target_: vc_models.transforms.vit_transforms
metadata:
  algo: 
  model: vit_large_patch16
  data:
    - ego
    - imagenet
    - inav
  comment: 182_epochs